export const APP_ERROR_CODES = [
  "UNAUTHENTICATED",
  "NOT_MEMBER",
  "OWNER_REQUIRED",
  "MEMBER_INACTIVE",
  "INVALID_PHASE",
  "INVALID_INPUT",
  "NOT_FOUND",
  "LIMIT_EXCEEDED",
  "CONFLICT",
  "STALE_PLANNING_CYCLE",
  "STALE_REVIEW_REVISION",
  "STALE_ITINERARY_VERSION",
  "VALIDATION_FAILED",
  "NEEDS_CONFIRMATION",
  "MAJORITY_REQUIRED",
  "APPROVAL_NOT_RESOLVED",
  "EXTERNAL_DATA_UNAVAILABLE",
  "FIXED_BOOKING_CONFLICT",
  "BUDGET_EXCEPTION_REQUIRED",
  "MUST_DO_CONFLICT",
  "INVITE_INVALID",
  "STALE_MEMBERSHIP_VERSION",
  "INVITE_RESET",
  "NO_SCHEDULABLE_CANDIDATES",
  "NO_FEASIBLE_OPTIONS",
  "MEMBERSHIP_FROZEN",
  "NOT_APPLICABLE_FOR_SOLO",
  "NO_ACTIVE_CANDIDATES",
  "CANDIDATE_INACTIVE",
  "NO_OPTION_VOTES",
] as const;

export type AppErrorCode = (typeof APP_ERROR_CODES)[number];

export interface AppErrorDetails {
  reason: AppErrorCode;
  tripId?: string;
  targetId?: string;
  reasonCodes?: string[];
}
