import type {
  Group,
  ItineraryDay,
  Member,
  Place,
  PlaceReview,
  Trip,
} from "./types";

// ---------------------------------------------------------------------------
// Members
// ---------------------------------------------------------------------------

export const MEMBERS: Record<string, Member> = {
  you: {
    id: "you",
    name: "You",
    initials: "Y",
    avatarColor: "var(--color-primary)",
    isYou: true,
    role: "organizer",
    hasSubmittedSuggestions: true,
    hasSubmittedVotes: true,
    preferences: {
      interests: ["Culture", "Food", "Photography", "History"],
      foodPreferences: ["Local Food", "Street Food", "Cafe"],
      pace: "Balanced",
      mustDo: [],
      dislikes: ["Long queues", "Very early mornings"],
      personalBudget: 2800,
    },
  },
  sarah: {
    id: "sarah",
    name: "Sarah",
    initials: "S",
    avatarColor: "#D8674A",
    role: "member",
    hasSubmittedSuggestions: true,
    hasSubmittedVotes: true,
    preferences: {
      interests: ["Shopping", "Food", "Nightlife", "Architecture"],
      foodPreferences: ["Fine Dining", "Dessert", "Cafe"],
      pace: "Fast-paced",
      mustDo: ["teamLab Borderless"],
      dislikes: ["Seafood", "Too much walking"],
      personalBudget: 3400,
    },
  },
  jason: {
    id: "jason",
    name: "Jason",
    initials: "J",
    avatarColor: "#3E7C7B",
    role: "member",
    hasSubmittedSuggestions: true,
    hasSubmittedVotes: true,
    preferences: {
      interests: ["Nature", "Relaxation"],
      foodPreferences: [],
      pace: "Balanced",
      mustDo: [],
      dislikes: ["Shopping malls"],
      personalBudget: 2200,
    },
  },
  daniel: {
    id: "daniel",
    name: "Daniel",
    initials: "D",
    avatarColor: "#8A5CF6",
    role: "member",
    hasSubmittedSuggestions: true,
    hasSubmittedVotes: true,
    preferences: {
      interests: ["History", "Museums", "Culture"],
      foodPreferences: ["Local Food", "Vegetarian"],
      pace: "Relaxed",
      mustDo: [],
      dislikes: ["Nightlife", "Crowded bars"],
      personalBudget: 2000,
    },
  },
  michelle: {
    id: "michelle",
    name: "Michelle",
    initials: "M",
    avatarColor: "#C2578B",
    role: "member",
    hasSubmittedSuggestions: true,
    hasSubmittedVotes: false,
    preferences: {
      interests: ["Relaxation", "Food", "Photography"],
      foodPreferences: ["Cafe", "Dessert", "Halal"],
      pace: "Relaxed",
      mustDo: [],
      dislikes: ["Theme parks"],
      personalBudget: 2600,
    },
  },
  aisyah: {
    id: "aisyah",
    name: "Aisyah",
    initials: "A",
    avatarColor: "#4C7BD9",
    role: "member",
    hasSubmittedSuggestions: false,
    hasSubmittedVotes: false,
    preferences: {
      interests: ["Food", "Culture", "Shopping"],
      foodPreferences: ["Halal", "Street Food"],
      pace: "Balanced",
      mustDo: [],
      dislikes: [],
      personalBudget: 2400,
    },
  },
  ray: {
    id: "ray",
    name: "Ray",
    initials: "R",
    avatarColor: "#3E7C7B",
    role: "member",
    hasSubmittedSuggestions: true,
    hasSubmittedVotes: true,
    preferences: {
      interests: ["Food", "Nightlife", "Photography"],
      foodPreferences: ["Street Food", "Local Food"],
      pace: "Fast-paced",
      mustDo: [],
      dislikes: [],
      personalBudget: 600,
    },
  },
  nadia: {
    id: "nadia",
    name: "Nadia",
    initials: "N",
    avatarColor: "#C2578B",
    role: "member",
    hasSubmittedSuggestions: true,
    hasSubmittedVotes: false,
    preferences: {
      interests: ["Shopping", "Food", "Relaxation"],
      foodPreferences: ["Halal", "Cafe"],
      pace: "Relaxed",
      mustDo: [],
      dislikes: [],
      personalBudget: 500,
    },
  },
  wei: {
    id: "wei",
    name: "Wei Xin",
    initials: "W",
    avatarColor: "#8A5CF6",
    role: "member",
    hasSubmittedSuggestions: false,
    hasSubmittedVotes: false,
  },
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function review(author: string, rating: number, text: string, date: string): PlaceReview {
  return { id: `${author}-${date}`, author, rating, text, date };
}

const GRADIENTS = [
  "linear-gradient(135deg,#F6D9B8,#E8622F)",
  "linear-gradient(135deg,#BFE3DE,#0E7C74)",
  "linear-gradient(135deg,#F3C7D6,#C2578B)",
  "linear-gradient(135deg,#CBD9F2,#4C7BD9)",
  "linear-gradient(135deg,#E4D6F7,#8A5CF6)",
  "linear-gradient(135deg,#F7E29B,#D8A62B)",
  "linear-gradient(135deg,#D6E8C7,#5C8A3A)",
  "linear-gradient(135deg,#F2C9BE,#D8674A)",
];

export function gradientFor(id: string) {
  let hash = 0;
  for (let i = 0; i < id.length; i++) hash = (hash * 31 + id.charCodeAt(i)) >>> 0;
  return GRADIENTS[hash % GRADIENTS.length];
}

// ---------------------------------------------------------------------------
// Places — Japan Adventure
// ---------------------------------------------------------------------------

export const JAPAN_PLACES: Place[] = [
  {
    id: "jp-senso-ji",
    name: "Senso-ji Temple",
    category: "Temple",
    area: "Asakusa",
    destination: "Tokyo",
    coordinates: { lat: 35.7148, lng: 139.7967 },
    address: "2 Chome-3-1 Asakusa, Taito City, Tokyo",
    photo: gradientFor("jp-senso-ji"),
    rating: 4.6,
    reviewCount: 12845,
    priceLevel: 1,
    priceLabel: "Free entry",
    description:
      "Tokyo's oldest and most celebrated Buddhist temple, founded in 645 AD. The iconic Kaminarimon Gate and five-story pagoda make it one of the most photographed sites in the city.",
    openingHours: [
      { day: "Mon–Sun", hours: "6:00 AM – 5:00 PM" },
    ],
    isOpenNow: true,
    closesAt: "5:00 PM",
    estimatedDurationMinutes: 90,
    reviews: [
      review("Haruto K.", 5, "Beautiful even with the crowds. Go early morning for the best photos.", "2 weeks ago"),
      review("Emma L.", 4, "Gorgeous temple grounds. Nakamise street right next to it is a bonus.", "1 month ago"),
    ],
    availability: "available",
    suggestedBy: ["you", "daniel"],
    voteCount: 6,
    votedBy: ["you", "sarah", "jason", "daniel", "michelle", "aisyah"],
  },
  {
    id: "jp-nakamise",
    name: "Nakamise Shopping Street",
    category: "Market",
    area: "Asakusa",
    destination: "Tokyo",
    coordinates: { lat: 35.7139, lng: 139.7966 },
    address: "Asakusa 1 Chome, Taito City, Tokyo",
    photo: gradientFor("jp-nakamise"),
    rating: 4.4,
    reviewCount: 8210,
    priceLevel: 1,
    priceLabel: "$ · Snacks from ¥300",
    description:
      "A 250-meter shopping street leading to Senso-ji, lined with traditional snacks, souvenirs and crafts. Great spot for melon pan and senbei.",
    openingHours: [{ day: "Mon–Sun", hours: "9:00 AM – 6:00 PM" }],
    isOpenNow: true,
    closesAt: "6:00 PM",
    estimatedDurationMinutes: 60,
    reviews: [review("Priya S.", 4, "Fun street food browsing, gets packed midday.", "3 weeks ago")],
    availability: "available",
    suggestedBy: ["sarah"],
    voteCount: 4,
    votedBy: ["you", "sarah", "michelle", "aisyah"],
  },
  {
    id: "jp-ueno-park",
    name: "Ueno Park",
    category: "Park",
    area: "Ueno",
    destination: "Tokyo",
    coordinates: { lat: 35.7156, lng: 139.7745 },
    address: "Uenokoen, Taito City, Tokyo",
    photo: gradientFor("jp-ueno-park"),
    rating: 4.5,
    reviewCount: 15320,
    priceLevel: 1,
    priceLabel: "Free entry",
    description:
      "Spacious public park home to museums, a zoo, a shrine, and Tokyo's most famous cherry blossom grounds. Calm green escape close to Asakusa.",
    openingHours: [{ day: "Mon–Sun", hours: "5:00 AM – 11:00 PM" }],
    isOpenNow: true,
    estimatedDurationMinutes: 90,
    reviews: [review("Marco T.", 5, "Peaceful walk, museums right inside the park too.", "1 week ago")],
    availability: "available",
    suggestedBy: ["you"],
    voteCount: 4,
    votedBy: ["you", "jason", "daniel", "michelle"],
  },
  {
    id: "jp-shibuya-crossing",
    name: "Shibuya Crossing",
    category: "Landmark",
    area: "Shibuya",
    destination: "Tokyo",
    coordinates: { lat: 35.6595, lng: 139.7005 },
    address: "2 Chome-2-1 Dogenzaka, Shibuya City, Tokyo",
    photo: gradientFor("jp-shibuya-crossing"),
    rating: 4.7,
    reviewCount: 22110,
    priceLevel: 1,
    priceLabel: "Free",
    description:
      "The world's busiest pedestrian scramble crossing — an unmissable only-in-Tokyo moment, best viewed from the Starbucks or Shibuya Sky above.",
    openingHours: [{ day: "Mon–Sun", hours: "Open 24 hours" }],
    isOpenNow: true,
    estimatedDurationMinutes: 45,
    reviews: [
      review("Sofia R.", 5, "Watching from the 2nd floor Starbucks is the move.", "4 days ago"),
      review("Kenji M.", 4, "Crazy energy at night, bring your camera.", "2 weeks ago"),
    ],
    availability: "available",
    suggestedBy: ["sarah", "jason"],
    voteCount: 5,
    votedBy: ["you", "sarah", "daniel", "michelle", "aisyah"],
  },
  {
    id: "jp-meiji-shrine",
    name: "Meiji Shrine",
    category: "Shrine",
    area: "Shibuya",
    destination: "Tokyo",
    coordinates: { lat: 35.6764, lng: 139.6993 },
    address: "1-1 Yoyogikamizonocho, Shibuya City, Tokyo",
    photo: gradientFor("jp-meiji-shrine"),
    rating: 4.6,
    reviewCount: 18040,
    priceLevel: 1,
    priceLabel: "Free entry",
    description:
      "A tranquil forested shrine dedicated to Emperor Meiji, tucked away just minutes from Harajuku's busy streets — a striking contrast of calm and chaos.",
    openingHours: [{ day: "Mon–Sun", hours: "5:00 AM – 6:00 PM" }],
    isOpenNow: true,
    closesAt: "6:00 PM",
    estimatedDurationMinutes: 75,
    reviews: [review("Aina Z.", 5, "So peaceful, the forest walk in feels like another world.", "5 days ago")],
    availability: "available",
    suggestedBy: ["daniel"],
    voteCount: 4,
    votedBy: ["you", "daniel", "michelle", "aisyah"],
  },
  {
    id: "jp-harajuku",
    name: "Harajuku Takeshita Street",
    category: "Shopping Street",
    area: "Shibuya",
    destination: "Tokyo",
    coordinates: { lat: 35.6702, lng: 139.7026 },
    address: "Jingumae, Shibuya City, Tokyo",
    photo: gradientFor("jp-harajuku"),
    rating: 4.3,
    reviewCount: 9870,
    priceLevel: 2,
    priceLabel: "$$ · Varies",
    description:
      "Tokyo's youth fashion capital — crepes, kawaii boutiques, and people-watching along a colorful pedestrian street.",
    openingHours: [{ day: "Mon–Sun", hours: "10:00 AM – 8:00 PM" }],
    isOpenNow: true,
    closesAt: "8:00 PM",
    estimatedDurationMinutes: 90,
    reviews: [review("Sarah P.", 4, "Crepes are a must. Very crowded on weekends.", "1 week ago")],
    availability: "available",
    suggestedBy: ["sarah"],
    voteCount: 3,
    votedBy: ["sarah", "michelle", "aisyah"],
  },
  {
    id: "jp-shinjuku-gyoen",
    name: "Shinjuku Gyoen",
    category: "Garden",
    area: "Shinjuku",
    destination: "Tokyo",
    coordinates: { lat: 35.6852, lng: 139.71 },
    address: "11 Naitomachi, Shinjuku City, Tokyo",
    photo: gradientFor("jp-shinjuku-gyoen"),
    rating: 4.7,
    reviewCount: 13400,
    priceLevel: 1,
    priceLabel: "¥500",
    description:
      "One of Tokyo's largest and most beautiful gardens, blending French, English and Japanese landscaping styles.",
    openingHours: [{ day: "Tue–Sun", hours: "9:00 AM – 4:30 PM" }],
    isOpenNow: false,
    closesAt: "4:30 PM",
    estimatedDurationMinutes: 100,
    reviews: [review("Wei X.", 5, "Worth the small entry fee, so quiet inside.", "3 weeks ago")],
    availability: "available",
    suggestedBy: ["daniel"],
    voteCount: 2,
    votedBy: ["daniel", "you"],
  },
  {
    id: "jp-tmg-building",
    name: "Tokyo Metropolitan Government Building",
    category: "Observation Deck",
    area: "Shinjuku",
    destination: "Tokyo",
    coordinates: { lat: 35.6896, lng: 139.6917 },
    address: "2 Chome-8-1 Nishishinjuku, Shinjuku City, Tokyo",
    photo: gradientFor("jp-tmg-building"),
    rating: 4.4,
    reviewCount: 7210,
    priceLevel: 1,
    priceLabel: "Free entry",
    description:
      "Free 202m-high observation decks with panoramic views of the city and, on clear days, Mount Fuji.",
    openingHours: [{ day: "Mon–Sun", hours: "9:30 AM – 10:30 PM" }],
    isOpenNow: true,
    closesAt: "10:30 PM",
    estimatedDurationMinutes: 60,
    reviews: [review("Daniel O.", 4, "Free and still an amazing view, go at sunset.", "2 months ago")],
    availability: "available",
    suggestedBy: ["you"],
    voteCount: 2,
    votedBy: ["you", "jason"],
  },
  {
    id: "jp-teamlab",
    name: "teamLab Borderless",
    category: "Digital Art Museum",
    area: "Azabudai",
    destination: "Tokyo",
    coordinates: { lat: 35.6626, lng: 139.7377 },
    address: "Azabudai Hills, Minato City, Tokyo",
    photo: gradientFor("jp-teamlab"),
    rating: 4.8,
    reviewCount: 31200,
    priceLevel: 3,
    priceLabel: "¥3,800",
    description:
      "An immersive, borderless digital art museum where installations flow between rooms and react to visitors. Book tickets in advance — this sells out fast.",
    openingHours: [{ day: "Mon–Sun", hours: "10:00 AM – 7:00 PM" }],
    isOpenNow: true,
    closesAt: "7:00 PM",
    estimatedDurationMinutes: 150,
    reviews: [
      review("Grace H.", 5, "Unreal experience, wear light colors for better photos.", "6 days ago"),
      review("Tomo I.", 5, "Book at least 2 weeks ahead, timeslots sell out.", "1 month ago"),
    ],
    availability: "limited",
    suggestedBy: ["you", "sarah"],
    voteCount: 3,
    votedBy: ["you", "sarah", "daniel"],
  },
  {
    id: "jp-skytree",
    name: "Tokyo Skytree",
    category: "Observation Tower",
    area: "Sumida",
    destination: "Tokyo",
    coordinates: { lat: 35.7101, lng: 139.8107 },
    address: "1 Chome-1-2 Oshiage, Sumida City, Tokyo",
    photo: gradientFor("jp-skytree"),
    rating: 4.5,
    reviewCount: 27600,
    priceLevel: 3,
    priceLabel: "¥2,100 – ¥3,400",
    description:
      "At 634m, one of the tallest towers in the world, with two observation decks offering sweeping views over the Sumida River and beyond.",
    openingHours: [{ day: "Mon–Sun", hours: "10:00 AM – 9:00 PM" }],
    isOpenNow: true,
    closesAt: "9:00 PM",
    estimatedDurationMinutes: 120,
    reviews: [review("Liam F.", 4, "Great views, a bit pricey for the top deck.", "2 weeks ago")],
    availability: "available",
    suggestedBy: ["jason"],
    voteCount: 4,
    votedBy: ["you", "sarah", "jason", "daniel"],
  },
  {
    id: "jp-ichiran",
    name: "Ichiran Ramen Shibuya",
    category: "Ramen",
    area: "Shibuya",
    destination: "Tokyo",
    coordinates: { lat: 35.659, lng: 139.7016 },
    address: "1 Chome-22-7 Jinnan, Shibuya City, Tokyo",
    photo: gradientFor("jp-ichiran"),
    rating: 4.3,
    reviewCount: 16700,
    priceLevel: 2,
    priceLabel: "¥1,000 – ¥1,500",
    description:
      "Famous solo-booth tonkotsu ramen chain. Order via vending machine, customize your broth — a Tokyo rite of passage.",
    openingHours: [{ day: "Mon–Sun", hours: "Open 24 hours" }],
    isOpenNow: true,
    estimatedDurationMinutes: 45,
    reviews: [review("Bella C.", 4, "Consistent and fast, love the individual booths.", "1 week ago")],
    availability: "available",
    suggestedBy: ["jason"],
    voteCount: 3,
    votedBy: ["jason", "you", "daniel"],
  },
  {
    id: "jp-tsukiji",
    name: "Tsukiji Outer Market",
    category: "Food Market",
    area: "Tsukiji",
    destination: "Tokyo",
    coordinates: { lat: 35.6654, lng: 139.7707 },
    address: "4 Chome-16-2 Tsukiji, Chuo City, Tokyo",
    photo: gradientFor("jp-tsukiji"),
    rating: 4.5,
    reviewCount: 19800,
    priceLevel: 2,
    priceLabel: "$$ · Street food",
    description:
      "Bustling market streets packed with fresh seafood stalls, tamagoyaki stands, and knife shops. Best visited on an empty stomach, early.",
    openingHours: [{ day: "Wed–Mon", hours: "5:00 AM – 2:00 PM" }],
    isOpenNow: true,
    closesAt: "2:00 PM",
    estimatedDurationMinutes: 90,
    reviews: [review("Noah B.", 5, "Grilled scallops and uni were incredible.", "3 weeks ago")],
    availability: "available",
    suggestedBy: ["michelle"],
    voteCount: 2,
    votedBy: ["michelle", "sarah"],
  },
  {
    id: "jp-fushimi-inari",
    name: "Fushimi Inari Shrine",
    category: "Shrine",
    area: "Fushimi",
    destination: "Kyoto",
    coordinates: { lat: 34.9671, lng: 135.7727 },
    address: "68 Fukakusa Yabunouchicho, Fushimi Ward, Kyoto",
    photo: gradientFor("jp-fushimi-inari"),
    rating: 4.8,
    reviewCount: 41200,
    priceLevel: 1,
    priceLabel: "Free entry",
    description:
      "Thousands of vermillion torii gates wind up Mount Inari. The full loop takes ~2-3 hours, but the first viewpoint alone is worth the visit.",
    openingHours: [{ day: "Mon–Sun", hours: "Open 24 hours" }],
    isOpenNow: true,
    estimatedDurationMinutes: 150,
    reviews: [
      review("Jason W.", 5, "Go at sunrise to skip the crowds, it's magical.", "1 week ago"),
      review("Yuki T.", 5, "The higher you climb the fewer people you see.", "2 weeks ago"),
    ],
    availability: "available",
    suggestedBy: ["jason", "you"],
    voteCount: 2,
    votedBy: ["you", "daniel"],
  },
  {
    id: "jp-arashiyama",
    name: "Arashiyama Bamboo Grove",
    category: "Nature",
    area: "Arashiyama",
    destination: "Kyoto",
    coordinates: { lat: 35.0094, lng: 135.6716 },
    address: "Sagaogurayama Tabuchiyamacho, Ukyo Ward, Kyoto",
    photo: gradientFor("jp-arashiyama"),
    rating: 4.5,
    reviewCount: 23900,
    priceLevel: 1,
    priceLabel: "Free entry",
    description:
      "A towering, otherworldly bamboo path. Short but stunning — pair it with the nearby Tenryu-ji temple gardens.",
    openingHours: [{ day: "Mon–Sun", hours: "Open 24 hours" }],
    isOpenNow: true,
    estimatedDurationMinutes: 60,
    reviews: [review("Chloe D.", 4, "Beautiful but very busy by 10am, go early.", "4 days ago")],
    availability: "available",
    suggestedBy: ["jason"],
    voteCount: 4,
    votedBy: ["jason", "you", "daniel", "michelle"],
  },
  {
    id: "jp-kinkakuji",
    name: "Kinkaku-ji (Golden Pavilion)",
    category: "Temple",
    area: "Kita",
    destination: "Kyoto",
    coordinates: { lat: 35.0394, lng: 135.7292 },
    address: "1 Kinkakujicho, Kita Ward, Kyoto",
    photo: gradientFor("jp-kinkakuji"),
    rating: 4.7,
    reviewCount: 29500,
    priceLevel: 1,
    priceLabel: "¥500",
    description:
      "A Zen temple whose top two floors are covered entirely in gold leaf, reflected perfectly in the surrounding pond.",
    openingHours: [{ day: "Mon–Sun", hours: "9:00 AM – 5:00 PM" }],
    isOpenNow: true,
    closesAt: "5:00 PM",
    estimatedDurationMinutes: 60,
    reviews: [review("Daniel O.", 5, "Even more striking in person, don't skip it.", "1 month ago")],
    availability: "available",
    suggestedBy: ["daniel"],
    voteCount: 2,
    votedBy: ["you", "daniel"],
  },
  {
    id: "jp-gion",
    name: "Gion District",
    category: "Historic District",
    area: "Gion",
    destination: "Kyoto",
    coordinates: { lat: 35.0037, lng: 135.7788 },
    address: "Gion, Higashiyama Ward, Kyoto",
    photo: gradientFor("jp-gion"),
    rating: 4.6,
    reviewCount: 20100,
    priceLevel: 2,
    priceLabel: "$$ · Varies",
    description:
      "Kyoto's famed geisha district — preserved wooden machiya houses, teahouses, and if you're lucky, a glimpse of a geiko heading to an appointment.",
    openingHours: [{ day: "Mon–Sun", hours: "Open 24 hours" }],
    isOpenNow: true,
    estimatedDurationMinutes: 90,
    reviews: [review("Emma L.", 4, "Beautiful streets at dusk, be respectful with photos.", "2 weeks ago")],
    availability: "available",
    suggestedBy: ["michelle"],
    voteCount: 3,
    votedBy: ["michelle", "daniel", "you"],
  },
  {
    id: "jp-osaka-castle",
    name: "Osaka Castle",
    category: "Castle",
    area: "Chuo",
    destination: "Osaka",
    coordinates: { lat: 34.6873, lng: 135.5262 },
    address: "1-1 Osakajo, Chuo Ward, Osaka",
    photo: gradientFor("jp-osaka-castle"),
    rating: 4.5,
    reviewCount: 33400,
    priceLevel: 2,
    priceLabel: "¥600",
    description:
      "A striking reconstructed castle set in a large park, with a museum inside detailing its samurai-era history.",
    openingHours: [{ day: "Mon–Sun", hours: "9:00 AM – 5:00 PM" }],
    isOpenNow: true,
    closesAt: "5:00 PM",
    estimatedDurationMinutes: 90,
    reviews: [review("Ken S.", 4, "The park grounds alone are worth the walk.", "3 weeks ago")],
    availability: "available",
    suggestedBy: ["you"],
    voteCount: 3,
    votedBy: ["you", "jason", "daniel"],
  },
  {
    id: "jp-dotonbori",
    name: "Dotonbori",
    category: "Entertainment District",
    area: "Chuo",
    destination: "Osaka",
    coordinates: { lat: 34.6687, lng: 135.5013 },
    address: "Dotonbori, Chuo Ward, Osaka",
    photo: gradientFor("jp-dotonbori"),
    rating: 4.6,
    reviewCount: 38700,
    priceLevel: 2,
    priceLabel: "$$ · Street food",
    description:
      "Neon-lit canal-side strip famous for the Glico Running Man sign, takoyaki stalls, and endless street food.",
    openingHours: [{ day: "Mon–Sun", hours: "Open 24 hours" }],
    isOpenNow: true,
    estimatedDurationMinutes: 120,
    reviews: [review("Sofia R.", 5, "Best takoyaki of the whole trip. So much energy at night.", "1 week ago")],
    availability: "available",
    suggestedBy: ["sarah", "michelle"],
    voteCount: 5,
    votedBy: ["sarah", "michelle", "you", "daniel", "aisyah"],
  },
  {
    id: "jp-usj",
    name: "Universal Studios Japan",
    category: "Theme Park",
    area: "Konohana",
    destination: "Osaka",
    coordinates: { lat: 34.6654, lng: 135.4323 },
    address: "2 Chome-1-33 Sakurajima, Konohana Ward, Osaka",
    photo: gradientFor("jp-usj"),
    rating: 4.6,
    reviewCount: 52300,
    priceLevel: 4,
    priceLabel: "¥8,600+",
    description:
      "Home to Super Nintendo World and Wizarding World of Harry Potter. Expect long queues — an Express Pass is strongly recommended.",
    openingHours: [{ day: "Mon–Sun", hours: "9:00 AM – 8:00 PM" }],
    isOpenNow: true,
    closesAt: "8:00 PM",
    estimatedDurationMinutes: 480,
    reviews: [review("Liam F.", 5, "Mario Kart ride is worth the hype, get there at opening.", "5 days ago")],
    availability: "limited",
    suggestedBy: ["sarah"],
    voteCount: 3,
    votedBy: ["sarah", "aisyah", "michelle"],
  },
];

// ---------------------------------------------------------------------------
// Places — Malaysia Long Weekend
// ---------------------------------------------------------------------------

export const MY_PLACES: Place[] = [
  {
    id: "my-klcc-park",
    name: "KLCC Park & Petronas Towers",
    category: "Landmark",
    area: "KLCC",
    destination: "Kuala Lumpur",
    coordinates: { lat: 3.1579, lng: 101.7116 },
    address: "Kuala Lumpur City Centre, 50450 Kuala Lumpur",
    photo: gradientFor("my-klcc-park"),
    rating: 4.7,
    reviewCount: 61200,
    priceLevel: 1,
    priceLabel: "Free park · RM80+ for tower",
    description:
      "Iconic twin towers with a landscaped park at their base and a fountain lake show at night.",
    openingHours: [{ day: "Mon–Sun", hours: "9:00 AM – 10:00 PM" }],
    isOpenNow: true,
    closesAt: "10:00 PM",
    estimatedDurationMinutes: 90,
    reviews: [review("Nadia R.", 5, "Fountain show at 8pm is beautiful, come early for a spot.", "1 week ago")],
    availability: "available",
    suggestedBy: ["you", "nadia"],
    voteCount: 2,
    votedBy: ["you", "ray"],
  },
  {
    id: "my-batu-caves",
    name: "Batu Caves",
    category: "Temple",
    area: "Gombak",
    destination: "Kuala Lumpur",
    coordinates: { lat: 3.2379, lng: 101.684 },
    address: "Gombak, 68100 Batu Caves, Selangor",
    photo: gradientFor("my-batu-caves"),
    rating: 4.5,
    reviewCount: 48300,
    priceLevel: 1,
    priceLabel: "Free entry",
    description:
      "A limestone hill with Hindu shrines inside, reached by climbing 272 colorful steps guarded by a giant golden statue.",
    openingHours: [{ day: "Mon–Sun", hours: "6:00 AM – 9:00 PM" }],
    isOpenNow: true,
    closesAt: "9:00 PM",
    estimatedDurationMinutes: 90,
    reviews: [review("Ray L.", 4, "The steps are a workout but the caves are worth it.", "2 weeks ago")],
    availability: "available",
    suggestedBy: ["ray"],
    voteCount: 1,
    votedBy: ["ray"],
  },
  {
    id: "my-bukit-bintang",
    name: "Bukit Bintang",
    category: "Shopping District",
    area: "Bukit Bintang",
    destination: "Kuala Lumpur",
    coordinates: { lat: 3.1466, lng: 101.7107 },
    address: "Bukit Bintang, 55100 Kuala Lumpur",
    photo: gradientFor("my-bukit-bintang"),
    rating: 4.4,
    reviewCount: 29800,
    priceLevel: 2,
    priceLabel: "$$ · Varies",
    description: "KL's busiest shopping and nightlife strip, packed with malls, street food, and rooftop bars.",
    openingHours: [{ day: "Mon–Sun", hours: "10:00 AM – 12:00 AM" }],
    isOpenNow: true,
    closesAt: "12:00 AM",
    estimatedDurationMinutes: 120,
    reviews: [review("You", 4, "Jalan Alor food street here is unmissable.", "3 days ago")],
    availability: "available",
    suggestedBy: ["you"],
    voteCount: 2,
    votedBy: ["you", "nadia"],
  },
  {
    id: "my-petaling-street",
    name: "Petaling Street (Chinatown)",
    category: "Market",
    area: "Chinatown",
    destination: "Kuala Lumpur",
    coordinates: { lat: 3.1435, lng: 101.6969 },
    address: "Petaling Street, 50000 Kuala Lumpur",
    photo: gradientFor("my-petaling-street"),
    rating: 4.2,
    reviewCount: 24500,
    priceLevel: 1,
    priceLabel: "$ · Street food",
    description: "Covered market street known for bargain shopping, herbal teas, and classic hawker fare.",
    openingHours: [{ day: "Mon–Sun", hours: "10:00 AM – 10:00 PM" }],
    isOpenNow: true,
    closesAt: "10:00 PM",
    estimatedDurationMinutes: 60,
    reviews: [review("Wei X.", 3, "Fun to browse, haggle for souvenirs.", "1 month ago")],
    availability: "available",
    suggestedBy: ["nadia"],
    voteCount: 1,
    votedBy: ["nadia"],
  },
  {
    id: "my-trx",
    name: "TRX & Exchange 106",
    category: "Shopping Mall",
    area: "TRX",
    destination: "Kuala Lumpur",
    coordinates: { lat: 3.1436, lng: 101.7192 },
    address: "Jalan Tun Razak, 55188 Kuala Lumpur",
    photo: gradientFor("my-trx"),
    rating: 4.6,
    reviewCount: 8100,
    priceLevel: 2,
    priceLabel: "$$ · Varies",
    description: "KL's newest financial and retail district, home to a rooftop park and Malaysia's tallest tower.",
    openingHours: [{ day: "Mon–Sun", hours: "10:00 AM – 10:00 PM" }],
    isOpenNow: true,
    closesAt: "10:00 PM",
    estimatedDurationMinutes: 90,
    reviews: [review("Ray L.", 4, "Impressive architecture, good food court too.", "2 weeks ago")],
    availability: "available",
    suggestedBy: ["ray"],
    voteCount: 1,
    votedBy: ["you"],
  },
  {
    id: "my-uptown-pj",
    name: "Uptown PJ",
    category: "Cafe District",
    area: "Petaling Jaya",
    destination: "Petaling Jaya",
    coordinates: { lat: 3.1073, lng: 101.6234 },
    address: "Uptown, 47400 Petaling Jaya, Selangor",
    photo: gradientFor("my-uptown-pj"),
    rating: 4.3,
    reviewCount: 5600,
    priceLevel: 2,
    priceLabel: "$$ · Cafes",
    description: "A relaxed cluster of cafes, antique shops and supper spots popular with PJ locals.",
    openingHours: [{ day: "Mon–Sun", hours: "8:00 AM – 11:00 PM" }],
    isOpenNow: true,
    closesAt: "11:00 PM",
    estimatedDurationMinutes: 90,
    reviews: [review("Nadia R.", 4, "Great supper spot after a night out in KL.", "1 week ago")],
    availability: "available",
    suggestedBy: ["you"],
    voteCount: 1,
    votedBy: ["nadia"],
  },
];

// ---------------------------------------------------------------------------
// Places — Bali Chill Trip (early stage / few suggestions)
// ---------------------------------------------------------------------------

export const BALI_PLACES: Place[] = [
  {
    id: "bali-uluwatu",
    name: "Uluwatu Temple",
    category: "Temple",
    area: "Uluwatu",
    destination: "Bali",
    coordinates: { lat: -8.8291, lng: 115.0849 },
    address: "Pecatu, South Kuta, Badung Regency, Bali",
    photo: gradientFor("bali-uluwatu"),
    rating: 4.7,
    reviewCount: 33800,
    priceLevel: 1,
    priceLabel: "IDR 50,000",
    description: "Clifftop temple with dramatic ocean views and traditional Kecak fire dance at sunset.",
    openingHours: [{ day: "Mon–Sun", hours: "8:00 AM – 7:00 PM" }],
    isOpenNow: true,
    closesAt: "7:00 PM",
    estimatedDurationMinutes: 120,
    reviews: [review("Wei X.", 5, "Sunset here is unbeatable, watch out for monkeys.", "2 weeks ago")],
    availability: "available",
    suggestedBy: ["you"],
    voteCount: 0,
    votedBy: [],
  },
  {
    id: "bali-tegallalang",
    name: "Tegallalang Rice Terraces",
    category: "Nature",
    area: "Ubud",
    destination: "Bali",
    coordinates: { lat: -8.4312, lng: 115.2789 },
    address: "Tegallalang, Gianyar Regency, Bali",
    photo: gradientFor("bali-tegallalang"),
    rating: 4.5,
    reviewCount: 21400,
    priceLevel: 1,
    priceLabel: "IDR 15,000",
    description: "Iconic terraced rice paddies on a steep valley, a classic Ubud postcard view.",
    openingHours: [{ day: "Mon–Sun", hours: "7:00 AM – 6:00 PM" }],
    isOpenNow: true,
    closesAt: "6:00 PM",
    estimatedDurationMinutes: 90,
    reviews: [review("Wei X.", 4, "Best light in the early morning.", "3 weeks ago")],
    availability: "available",
    suggestedBy: ["wei"],
    voteCount: 0,
    votedBy: [],
  },
];

export const ALL_PLACES: Record<string, Place> = Object.fromEntries(
  [...JAPAN_PLACES, ...MY_PLACES, ...BALI_PLACES].map((p) => [p.id, p])
);

// Derive each member's suggestedPlaceIds / votedPlaceIds from the place data
// above, so the two stay in sync without listing every id twice.
for (const place of Object.values(ALL_PLACES)) {
  for (const memberId of place.suggestedBy) {
    const m = MEMBERS[memberId];
    if (!m) continue;
    m.suggestedPlaceIds = m.suggestedPlaceIds ?? [];
    if (!m.suggestedPlaceIds.includes(place.id)) m.suggestedPlaceIds.push(place.id);
  }
  for (const memberId of place.votedBy) {
    const m = MEMBERS[memberId];
    if (!m) continue;
    m.votedPlaceIds = m.votedPlaceIds ?? [];
    if (!m.votedPlaceIds.includes(place.id)) m.votedPlaceIds.push(place.id);
  }
}

// ---------------------------------------------------------------------------
// Groups
// ---------------------------------------------------------------------------

export const GROUPS: Group[] = [
  {
    id: "grp-japan",
    name: "Japan Adventure",
    emoji: "🗼",
    coverColor: "linear-gradient(135deg,#2D3B55,#0E7C74)",
    description: "The annual year-end trip crew. Ramen, temples, and chaos guaranteed.",
    memberIds: ["you", "sarah", "jason", "daniel", "michelle", "aisyah"],
    tripIds: ["trip-japan"],
  },
  {
    id: "grp-kl",
    name: "KL Weekend Squad",
    emoji: "🏙️",
    coverColor: "linear-gradient(135deg,#4C7BD9,#8A5CF6)",
    description: "Quick getaways whenever someone's free on a long weekend.",
    memberIds: ["you", "ray", "nadia"],
    tripIds: ["trip-kl"],
  },
  {
    id: "grp-bali",
    name: "Weekend Warriors",
    emoji: "🌴",
    coverColor: "linear-gradient(135deg,#D8A62B,#D8674A)",
    description: "Chasing sun, surf and good food.",
    memberIds: ["you", "wei"],
    tripIds: ["trip-bali"],
  },
];

// ---------------------------------------------------------------------------
// Itinerary — Japan Adventure
// ---------------------------------------------------------------------------

const JAPAN_ITINERARY: ItineraryDay[] = [
  {
    day: 1,
    date: "2026-12-28",
    title: "Asakusa & Ueno",
    activities: [
      { id: "d1-a1", placeId: null, label: "Breakfast near hotel", time: "08:00", durationMinutes: 45, travelFromPrevMinutes: 0, estimatedCost: 12, type: "meal" },
      { id: "d1-a2", placeId: "jp-senso-ji", label: "Senso-ji Temple", time: "09:00", durationMinutes: 90, travelFromPrevMinutes: 20, estimatedCost: 0, type: "place", locked: true },
      { id: "d1-a3", placeId: "jp-nakamise", label: "Nakamise Shopping Street", time: "11:00", durationMinutes: 60, travelFromPrevMinutes: 5, estimatedCost: 15, type: "place" },
      { id: "d1-a4", placeId: null, label: "Lunch — local soba", time: "13:00", durationMinutes: 60, travelFromPrevMinutes: 15, estimatedCost: 18, type: "meal" },
      { id: "d1-a5", placeId: "jp-ueno-park", label: "Ueno Park", time: "15:00", durationMinutes: 90, travelFromPrevMinutes: 20, estimatedCost: 0, type: "place" },
      { id: "d1-a6", placeId: null, label: "Return to hotel", time: "18:00", durationMinutes: 30, travelFromPrevMinutes: 25, estimatedCost: 4, type: "transit" },
    ],
  },
  {
    day: 2,
    date: "2026-12-29",
    title: "Shibuya, Harajuku & Shinjuku",
    activities: [
      { id: "d2-a1", placeId: null, label: "Breakfast near hotel", time: "08:30", durationMinutes: 30, travelFromPrevMinutes: 0, estimatedCost: 10, type: "meal" },
      { id: "d2-a2", placeId: "jp-meiji-shrine", label: "Meiji Shrine", time: "09:30", durationMinutes: 75, travelFromPrevMinutes: 25, estimatedCost: 0, type: "place" },
      { id: "d2-a3", placeId: "jp-harajuku", label: "Harajuku Takeshita Street", time: "11:00", durationMinutes: 90, travelFromPrevMinutes: 10, estimatedCost: 20, type: "place" },
      { id: "d2-a4", placeId: "jp-ichiran", label: "Lunch — Ichiran Ramen", time: "13:00", durationMinutes: 45, travelFromPrevMinutes: 15, estimatedCost: 14, type: "place" },
      { id: "d2-a5", placeId: "jp-shibuya-crossing", label: "Shibuya Crossing", time: "14:30", durationMinutes: 45, travelFromPrevMinutes: 10, estimatedCost: 0, type: "place", locked: true },
      { id: "d2-a6", placeId: "jp-tmg-building", label: "Tokyo Gov't Building Observatory", time: "16:30", durationMinutes: 60, travelFromPrevMinutes: 20, estimatedCost: 0, type: "place" },
      { id: "d2-a7", placeId: null, label: "Dinner in Shinjuku", time: "19:00", durationMinutes: 75, travelFromPrevMinutes: 10, estimatedCost: 28, type: "meal" },
    ],
  },
  {
    day: 3,
    date: "2026-12-30",
    title: "teamLab & Skytree",
    activities: [
      { id: "d3-a1", placeId: null, label: "Breakfast near hotel", time: "08:30", durationMinutes: 30, travelFromPrevMinutes: 0, estimatedCost: 10, type: "meal" },
      { id: "d3-a2", placeId: "jp-teamlab", label: "teamLab Borderless", time: "10:00", durationMinutes: 150, travelFromPrevMinutes: 30, estimatedCost: 28, type: "place", locked: true },
      { id: "d3-a3", placeId: null, label: "Lunch nearby", time: "13:00", durationMinutes: 60, travelFromPrevMinutes: 10, estimatedCost: 16, type: "meal" },
      { id: "d3-a4", placeId: "jp-skytree", label: "Tokyo Skytree", time: "15:30", durationMinutes: 120, travelFromPrevMinutes: 35, estimatedCost: 22, type: "place" },
      { id: "d3-a5", placeId: null, label: "Dinner + return", time: "18:30", durationMinutes: 90, travelFromPrevMinutes: 15, estimatedCost: 24, type: "meal" },
    ],
  },
  {
    day: 4,
    date: "2026-12-31",
    title: "Travel to Kyoto & Fushimi Inari",
    activities: [
      { id: "d4-a1", placeId: null, label: "Shinkansen to Kyoto", time: "08:00", durationMinutes: 150, travelFromPrevMinutes: 0, estimatedCost: 95, type: "transit", locked: true },
      { id: "d4-a2", placeId: null, label: "Check in & lunch", time: "11:00", durationMinutes: 60, travelFromPrevMinutes: 15, estimatedCost: 15, type: "meal" },
      { id: "d4-a3", placeId: "jp-fushimi-inari", label: "Fushimi Inari Shrine", time: "13:00", durationMinutes: 150, travelFromPrevMinutes: 20, estimatedCost: 0, type: "place", locked: true },
      { id: "d4-a4", placeId: null, label: "New Year's Eve dinner", time: "19:00", durationMinutes: 120, travelFromPrevMinutes: 25, estimatedCost: 40, type: "meal" },
    ],
  },
  {
    day: 5,
    date: "2027-01-01",
    title: "Arashiyama & Kinkaku-ji",
    activities: [
      { id: "d5-a1", placeId: null, label: "Breakfast near hotel", time: "08:30", durationMinutes: 30, travelFromPrevMinutes: 0, estimatedCost: 10, type: "meal" },
      { id: "d5-a2", placeId: "jp-arashiyama", label: "Arashiyama Bamboo Grove", time: "09:30", durationMinutes: 60, travelFromPrevMinutes: 30, estimatedCost: 0, type: "place" },
      { id: "d5-a3", placeId: "jp-kinkakuji", label: "Kinkaku-ji (Golden Pavilion)", time: "11:30", durationMinutes: 60, travelFromPrevMinutes: 25, estimatedCost: 4, type: "place" },
      { id: "d5-a4", placeId: null, label: "Lunch", time: "13:00", durationMinutes: 60, travelFromPrevMinutes: 15, estimatedCost: 16, type: "meal" },
      { id: "d5-a5", placeId: "jp-gion", label: "Gion District", time: "15:00", durationMinutes: 90, travelFromPrevMinutes: 20, estimatedCost: 10, type: "place" },
      { id: "d5-a6", placeId: null, label: "Dinner + return", time: "18:30", durationMinutes: 90, travelFromPrevMinutes: 15, estimatedCost: 26, type: "meal" },
    ],
  },
  {
    day: 6,
    date: "2027-01-02",
    title: "Osaka Day Trip",
    activities: [
      { id: "d6-a1", placeId: null, label: "Train to Osaka", time: "08:00", durationMinutes: 45, travelFromPrevMinutes: 0, estimatedCost: 16, type: "transit" },
      { id: "d6-a2", placeId: "jp-osaka-castle", label: "Osaka Castle", time: "09:00", durationMinutes: 90, travelFromPrevMinutes: 15, estimatedCost: 5, type: "place" },
      { id: "d6-a3", placeId: null, label: "Lunch", time: "11:00", durationMinutes: 60, travelFromPrevMinutes: 20, estimatedCost: 15, type: "meal" },
      { id: "d6-a4", placeId: "jp-dotonbori", label: "Dotonbori", time: "13:00", durationMinutes: 120, travelFromPrevMinutes: 20, estimatedCost: 20, type: "place" },
      { id: "d6-a5", placeId: null, label: "Return to Kyoto", time: "18:00", durationMinutes: 45, travelFromPrevMinutes: 15, estimatedCost: 16, type: "transit" },
    ],
  },
  {
    day: 7,
    date: "2027-01-03",
    title: "Departure",
    activities: [
      { id: "d7-a1", placeId: null, label: "Breakfast & pack", time: "08:00", durationMinutes: 60, travelFromPrevMinutes: 0, estimatedCost: 10, type: "meal" },
      { id: "d7-a2", placeId: null, label: "Souvenir shopping", time: "10:00", durationMinutes: 90, travelFromPrevMinutes: 15, estimatedCost: 40, type: "free" },
      { id: "d7-a3", placeId: null, label: "Transfer to airport", time: "13:00", durationMinutes: 90, travelFromPrevMinutes: 20, estimatedCost: 25, type: "transit", locked: true },
    ],
  },
];

// ---------------------------------------------------------------------------
// Trips
// ---------------------------------------------------------------------------

export const TRIPS: Record<string, Trip> = {
  "trip-japan": {
    id: "trip-japan",
    groupId: "grp-japan",
    name: "Japan Adventure",
    destinations: ["Tokyo", "Kyoto", "Osaka"],
    coverColor: "linear-gradient(135deg,#2D3B55,#0E7C74)",
    startDate: "2026-12-28",
    endDate: "2027-01-03",
    budgetTotal: 14700,
    groupSize: 6,
    dailyStart: "08:00",
    dailyEnd: "22:00",
    transport: "Mixed",
    stage: "itinerary",
    memberIds: ["you", "sarah", "jason", "daniel", "michelle", "aisyah"],
    placeIds: JAPAN_PLACES.map((p) => p.id),
    shortlistPlaceIds: [
      "jp-senso-ji",
      "jp-nakamise",
      "jp-ueno-park",
      "jp-shibuya-crossing",
      "jp-meiji-shrine",
      "jp-harajuku",
      "jp-tmg-building",
      "jp-teamlab",
      "jp-skytree",
      "jp-fushimi-inari",
      "jp-arashiyama",
      "jp-kinkakuji",
      "jp-gion",
      "jp-osaka-castle",
      "jp-dotonbori",
    ],
    recommendedPlaceCount: 8,
    votesPerMember: 16,
    itinerary: JAPAN_ITINERARY,
    itineraryRevision: 1,
    pricePressure: {
      level: "VERY HIGH",
      reasons: [
        "Year-end & New Year holiday period",
        "School holiday overlap",
        "Major local events (NYE countdowns)",
        "Limited availability on key attractions",
        "Visit date is approaching (under 4 months away)",
      ],
      recommendation: "Book Early",
    },
    rescueEvents: [
      {
        id: "rescue-1",
        type: "sold_out",
        message: "teamLab Borderless (3:00 PM) is showing sold out for your visit date.",
        affectedActivityId: "d3-a2",
        createdAt: "2026-12-30T07:40:00",
        status: "open",
        alternative: {
          placeId: "jp-tmg-building",
          label: "Tokyo Metropolitan Government Building",
          extraTravelMinutes: 10,
          available: true,
          cost: 0,
          note: "Keeps the day in Tokyo with limited disruption",
        },
      },
    ],
    isLive: true,
  },
  "trip-kl": {
    id: "trip-kl",
    groupId: "grp-kl",
    name: "Malaysia Long Weekend",
    destinations: ["Kuala Lumpur", "Petaling Jaya"],
    coverColor: "linear-gradient(135deg,#4C7BD9,#8A5CF6)",
    startDate: "2026-10-10",
    endDate: "2026-10-12",
    budgetTotal: 1500,
    groupSize: 3,
    dailyStart: "09:00",
    dailyEnd: "23:00",
    transport: "Car",
    stage: "voting",
    memberIds: ["you", "ray", "nadia"],
    placeIds: MY_PLACES.map((p) => p.id),
    shortlistPlaceIds: [],
    recommendedPlaceCount: 6,
    votesPerMember: 5,
    itinerary: [],
    itineraryRevision: 1,
    pricePressure: {
      level: "MEDIUM",
      reasons: ["Weekend travel dates", "Moderate demand for city hotels"],
      recommendation: "Book Soon",
    },
    rescueEvents: [],
  },
  "trip-bali": {
    id: "trip-bali",
    groupId: "grp-bali",
    name: "Bali Chill Trip",
    destinations: ["Bali"],
    coverColor: "linear-gradient(135deg,#D8A62B,#D8674A)",
    startDate: "2027-03-14",
    endDate: "2027-03-19",
    budgetTotal: 3200,
    groupSize: 2,
    dailyStart: "08:00",
    dailyEnd: "21:00",
    transport: "Mixed",
    stage: "ideas",
    memberIds: ["you", "wei"],
    placeIds: BALI_PLACES.map((p) => p.id),
    shortlistPlaceIds: [],
    recommendedPlaceCount: 8,
    votesPerMember: 8,
    itinerary: [],
    itineraryRevision: 1,
    pricePressure: {
      level: "LOW",
      reasons: ["Visit date is well in advance", "Off-peak shoulder season"],
      recommendation: "No rush yet",
    },
    rescueEvents: [],
  },
};

export const CURRENT_USER_ID = "you";
